from enum import Enum


class ErrorType(str, Enum):
    INVALID_INPUT = "INVALID_INPUT"
    INTENT_CLASSIFICATION_ERROR = "INTENT_CLASSIFICATION_ERROR"
    DISAMBIGUATION_REQUIRED = "DISAMBIGUATION_REQUIRED"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    INVALID_TRANSITION = "INVALID_TRANSITION"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
